import { 
  Transaction, 
  Policy, 
  PolicyProposal, 
  DecisionTrace, 
  AuditRecord, 
  EvaluationReport,
  Vendor,
  PurchaseOrder,
  Invoice,
  DataSourceItem,
  ConnectorItem,
  ControlPlaneAgentRun
} from './types';

export const INITIAL_POLICIES: Policy[] = [
  {
    id: "POL-VAR-001",
    name: "Standard PO Variance Tolerance",
    category: "VARIANCE",
    description: "Invoice variances up to 2.0% against approved Purchase Orders can be auto-cleared.",
    rule_expression: "variance_pct <= 2.0",
    threshold_value: 2.0,
    is_active: true,
    version: 1,
  },
  {
    id: "POL-DUP-001",
    name: "Duplicate Invoice Prevention",
    category: "DUPLICATE",
    description: "Any transaction with duplicate score >= 0.85 must be blocked.",
    rule_expression: "duplicate_score >= 0.85",
    threshold_value: 0.85,
    is_active: true,
    version: 1,
  },
  {
    id: "POL-MAT-001",
    name: "Materiality Escalation Threshold",
    category: "MATERIALITY",
    description: "Discrepancies equal to or exceeding $10,000.00 (or ₹10,00,000 equivalent) require Controller sign-off.",
    rule_expression: "amount >= 10000.0",
    threshold_value: 10000.0,
    is_active: true,
    version: 1,
  },
  {
    id: "POL-GL-001",
    name: "Vendor Chart of Accounts Consistency",
    category: "CLASSIFICATION",
    description: "Transactions must match the master GL account specified in vendor master agreements.",
    rule_expression: "gl_account == vendor_master_gl",
    threshold_value: 1.0,
    is_active: true,
    version: 1,
  },
  {
    id: "POL-FX-001",
    name: "FX Variance Revaluation Buffer",
    category: "FX_TOLERANCE",
    description: "Cross-currency settlement variance within 1.5% auto-books to FX Gain/Loss; >1.5% escalates.",
    rule_expression: "fx_variance_pct <= 1.5",
    threshold_value: 1.5,
    is_active: true,
    version: 1,
  },
];

export const INITIAL_PROPOSALS: PolicyProposal[] = [
  {
    proposal_id: "PROP-CW-001",
    policy_id: "POL-CW-SUGG",
    title: "Adjust CloudWorks Usage Variance Ceiling",
    current_rule: "Standard PO Variance Tolerance <= 2.0% (POL-VAR-001)",
    suggested_rule: "For verified CloudWorks Infrastructure contracts, allow <= 5.0% variance",
    reasoning: "5 consecutive monthly CloudWorks invoices between 2.1% and 4.8% variance were manually approved by Controller due to seasonal autoscaling. Updating this policy reduces routine manual close reviews by an estimated 14 hours annually.",
    supporting_evidence: [
      "TX-EXC-002: Approved by Controller on 2026-09-18 (3.0% variance)",
      "TX-HIST-881: Approved by Controller on 2026-08-15 (4.2% variance)",
      "TX-HIST-882: Approved by Controller on 2026-07-16 (3.8% variance)",
      "TX-HIST-883: Approved by Controller on 2026-06-14 (4.5% variance)",
      "TX-HIST-884: Approved by Controller on 2026-05-15 (2.9% variance)",
    ],
    projected_manual_reviews_reduced_pct: 18.5,
    requires_human_approval: true,
    status: "PENDING_HUMAN_APPROVAL",
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // Intentional Exceptions
  {
    id: "TX-EXC-001",
    date: "2026-09-15",
    vendor: "Starlight Logistics",
    description: "Logistics invoice payment request - duplicate submission",
    amount: 14500.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6300 - Freight & Shipping",
    status: "BLOCKED",
    invoice_ref: "INV-STR-4401-DUP",
    po_ref: "PO-9002",
    category: "DUPLICATE_INVOICE",
    confidence: 0.98,
    risk_tier: "TIER_D",
    trace_id: "TRC-DUP-001",
    notes: "Exact match to invoice INV-STR-4401 already cleared on Sep 2.",
  },
  {
    id: "TX-EXC-002",
    date: "2026-09-18",
    vendor: "Apex Consulting Group",
    description: "Enterprise ERP advisory milestone billing",
    amount: 103000.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6120 - Professional Services & Legal",
    status: "EXCEPTION",
    invoice_ref: "INV-APX-8802",
    po_ref: "PO-9001",
    category: "PO_VARIANCE",
    confidence: 0.92,
    risk_tier: "TIER_C",
    trace_id: "TRC-VAR-002",
    notes: "3% variance ($3,000) exceeds POL-VAR-001 2% threshold. Material amount requires Controller approval.",
  },
  {
    id: "TX-EXC-003",
    date: "2026-09-04",
    vendor: "Amazon Web Services",
    description: "Monthly us-east-1 compute cluster consumption",
    amount: 8420.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6400 - Office Supplies & Administration", // Erroneous
    status: "EXCEPTION",
    invoice_ref: "INV-AWS-9910",
    category: "GL_MISCLASSIFICATION",
    confidence: 0.94,
    risk_tier: "TIER_D",
    trace_id: "TRC-GL-003",
    notes: "Resolution Agent proposed Office Supplies; Independent Verifier blocked execution and flagged Cloud Infrastructure.",
  },
  {
    id: "TX-EXC-004",
    date: "2026-09-28",
    vendor: "Datadog Operations",
    description: "Monthly infrastructure monitoring AP balance",
    amount: 4200.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6020 - Software & SaaS Subscriptions",
    status: "EXCEPTION",
    category: "MISSING_DOCUMENT",
    confidence: 0.89,
    risk_tier: "TIER_C",
    trace_id: "TRC-ACC-004",
    notes: "Recurring SaaS with active contract, but invoice not yet uploaded. Propose accrual journal entry.",
  },
  {
    id: "TX-EXC-005",
    date: "2026-09-20",
    vendor: "Unknown Global Ventures",
    description: "International offshore data conversion service",
    amount: 18500.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "9999 - Suspense Clearing",
    status: "EXCEPTION",
    invoice_ref: "INV-UNK-009",
    category: "UNSUPPORTED_VENDOR",
    confidence: 0.93,
    risk_tier: "TIER_C",
    trace_id: "TRC-UNK-005",
    notes: "No master agreement or verified tax ID on file. Escalated for vendor compliance audit.",
  },
  {
    id: "TX-EXC-006",
    date: "2026-09-22",
    vendor: "Tokyo Hardware Ltd",
    description: "Laboratory test fixture imported from Japan (¥2,205,000 JPY)",
    amount: 14210.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "1500 - Lab Equipment & Hardware",
    status: "EXCEPTION",
    invoice_ref: "INV-TYO-991",
    category: "FX_VARIANCE",
    confidence: 0.90,
    risk_tier: "TIER_C",
    trace_id: "TRC-FX-006",
    notes: "JPY conversion exchange rate differential (+1.8%). Requires standard FX revaluation review.",
    amount_original: 2205000,
    currency_original: "JPY",
    fx_rate: 155.2,
    fx_rate_source: "Reference FX rate (ECB benchmark)",
    fx_rate_date: "2026-09-22"
  },
  {
    id: "TX-EXC-007",
    date: "2026-09-25",
    vendor: "Delta Air Lines",
    description: "Executive ticket SFO-JFK customer summit",
    amount: 1250.0,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6500 - Travel & Entertainment",
    status: "EXCEPTION",
    category: "MISSING_RECEIPT",
    confidence: 0.87,
    risk_tier: "TIER_C",
    trace_id: "TRC-REC-007",
    notes: "Travel charge over $500 missing itemized tax receipt. Auto-request documentation.",
  },
  // Multi-Currency & Indian Formatting Demo Transactions
  {
    id: "TX-INR-001",
    date: "2026-09-12",
    vendor: "Tata Consultancy Services",
    description: "Cloud ERP implementation Sprint 14 milestone (₹12,50,000)",
    amount: 14966.48,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6120 - Professional Services & Legal",
    status: "RECONCILED",
    invoice_ref: "INV-TCS-9014",
    po_ref: "PO-TCS-004",
    confidence: 0.97,
    risk_tier: "TIER_B",
    notes: "INR converted at reference rate 83.52. 3-way matched to PO-TCS-004.",
    amount_original: 1250000.0,
    currency_original: "INR",
    fx_rate: 83.52,
    fx_rate_source: "Reference FX rate (RBI Reference Rate)",
    fx_rate_date: "2026-09-12"
  },
  {
    id: "TX-INR-002",
    date: "2026-09-19",
    vendor: "Infosys Cloud Solutions",
    description: "Offshore DevOps engineering retainer (₹4,85,000)",
    amount: 5807.00,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6020 - Software & SaaS Subscriptions",
    status: "RECONCILED",
    invoice_ref: "INV-INF-4420",
    confidence: 0.98,
    risk_tier: "TIER_B",
    notes: "INR settlement auto-reconciled against bank debit voucher.",
    amount_original: 485000.0,
    currency_original: "INR",
    fx_rate: 83.52,
    fx_rate_source: "Reference FX rate",
    fx_rate_date: "2026-09-19"
  },
  {
    id: "TX-EUR-001",
    date: "2026-09-08",
    vendor: "SAP SE Walldorf",
    description: "SAP S/4HANA Enterprise Cloud annual core license (€18,500)",
    amount: 20076.00,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6020 - Software & SaaS Subscriptions",
    status: "RECONCILED",
    invoice_ref: "INV-SAP-10928",
    po_ref: "PO-SAP-001",
    confidence: 0.99,
    risk_tier: "TIER_B",
    notes: "EUR wire cleared through European subledger.",
    amount_original: 18500.0,
    currency_original: "EUR",
    fx_rate: 0.9215,
    fx_rate_source: "Reference FX rate (ECB)",
    fx_rate_date: "2026-09-08"
  },
  {
    id: "TX-GBP-001",
    date: "2026-09-14",
    vendor: "London Telecom UK",
    description: "UK data center dark fiber link lease (£8,200)",
    amount: 10459.18,
    currency: "USD",
    type: "DEBIT",
    gl_account: "6210 - Utilities & Internet",
    status: "RECONCILED",
    invoice_ref: "INV-LT-771",
    confidence: 0.96,
    risk_tier: "TIER_B",
    notes: "GBP direct debit matched against monthly telecomm contract.",
    amount_original: 8200.0,
    currency_original: "GBP",
    fx_rate: 0.784,
    fx_rate_source: "Reference FX rate (BoE)",
    fx_rate_date: "2026-09-14"
  },
  {
    id: "TX-CHF-001",
    date: "2026-09-16",
    vendor: "Zurich Precision Instruments",
    description: "Optical calibration chamber sensor hardware (CHF 12,400)",
    amount: 14019.22,
    currency: "USD",
    type: "DEBIT",
    gl_account: "1500 - Lab Equipment & Hardware",
    status: "RECONCILED",
    invoice_ref: "INV-ZUR-092",
    confidence: 0.95,
    risk_tier: "TIER_B",
    notes: "Swiss Franc invoice validated against customs clearance declaration.",
    amount_original: 12400.0,
    currency_original: "CHF",
    fx_rate: 0.8845,
    fx_rate_source: "Reference FX rate (SNB)",
    fx_rate_date: "2026-09-16"
  }
];

// Clean baseline recurring transactions
const cleanVendors = [
  { v: "Google Workspace", gl: "6020 - Software & SaaS Subscriptions", amt: 1250.0, d: "Monthly enterprise email & office suite" },
  { v: "Slack Technologies", gl: "6020 - Software & SaaS Subscriptions", amt: 980.0, d: "Enterprise communication platform" },
  { v: "Zoom Video Communications", gl: "6020 - Software & SaaS Subscriptions", amt: 450.0, d: "Video conferencing webinar licenses" },
  { v: "GitHub Enterprise", gl: "6020 - Software & SaaS Subscriptions", amt: 840.0, d: "Source code repositories & CI runners" },
  { v: "WeWork Global Spaces", gl: "6200 - Rent & Facilities", amt: 12800.0, d: "HQ office lease monthly rent" },
  { v: "Pacific Gas & Electric", gl: "6210 - Utilities & Internet", amt: 2140.0, d: "Building power & utility bill" },
  { v: "Comcast Business", gl: "6210 - Utilities & Internet", amt: 650.0, d: "Dedicated gigabit fiber line" },
  { v: "Gusto Payroll Services", gl: "6100 - Payroll Processing Fees", amt: 340.0, d: "Bi-weekly payroll tax processing fees" },
  { v: "FedEx Express", gl: "6300 - Freight & Shipping", amt: 285.0, d: "Express overnight prototype shipment" },
  { v: "Figma Enterprise", gl: "6020 - Software & SaaS Subscriptions", amt: 1800.0, d: "Design team product licenses" },
  { v: "Notion Labs", gl: "6020 - Software & SaaS Subscriptions", amt: 600.0, d: "Internal engineering wiki knowledge base" },
  { v: "Stripe Processing", gl: "6110 - Merchant & Bank Fees", amt: 1920.0, d: "Payment gateway interchange merchant fee" },
];

for (let day = 1; day <= 28; day++) {
  const item = cleanVendors[(day - 1) % cleanVendors.length];
  INITIAL_TRANSACTIONS.push({
    id: `TX-REC-${String(day).padStart(3, '0')}A`,
    date: `2026-09-${String(day).padStart(2, '0')}`,
    vendor: item.v,
    description: item.d,
    amount: Number((item.amt + day * 3.5).toFixed(2)),
    currency: "USD",
    type: "DEBIT",
    gl_account: item.gl,
    status: "RECONCILED",
    invoice_ref: `INV-${day}`,
    confidence: 0.99,
    risk_tier: "TIER_A",
    notes: "Auto-matched 3-way reconciliation verified against bank and AP subledger.",
  });

  if (day % 2 === 0) {
    INITIAL_TRANSACTIONS.push({
      id: `TX-REC-${String(day).padStart(3, '0')}B`,
      date: `2026-09-${String(day).padStart(2, '0')}`,
      vendor: "Silicon Valley Bank",
      description: "Customer accounts receivable wire deposit",
      amount: Number((8500.0 + day * 150.0).toFixed(2)),
      currency: "USD",
      type: "CREDIT",
      gl_account: "1100 - Operating Cash",
      status: "RECONCILED",
      confidence: 1.0,
      risk_tier: "TIER_A",
      notes: "Verified against incoming customer wire remittance advice.",
    });
  }
}

// Hero Judge Wow Moment Decision Trace for AWS TX-EXC-003
export const WOW_DECISION_TRACE: DecisionTrace = {
  trace_id: "TRC-GL-003",
  transaction_id: "TX-EXC-003",
  timestamp: "2026-09-05T10:14:22Z",
  investigation: {
    summary: "Investigated transaction TX-EXC-003 (Amazon Web Services, $8,420.00). Forensic analysis identified keyword ambiguity.",
    root_cause: "Resolution Agent proposed '6400 - Office Supplies', but historical records show consistent cloud hosting.",
    confidence: 0.94,
    recommended_action: "CORRECT_GL_POSTING",
    missing_evidence: [],
    evidence_gathered: [
      {
        id: "EVD-AWS-001",
        source_type: "VENDOR_MASTER_AGREEMENT",
        title: "AWS Enterprise Agreement (Executed 2024-03)",
        details: "Section 4.1 specifies all cloud compute, S3, and RDS billing maps strictly to GL 6020 (Cloud Infrastructure & SaaS).",
        relevance_score: 0.99,
      },
      {
        id: "EVD-AWS-002",
        source_type: "HISTORICAL_LEDGER",
        title: "Prior 12-Month AWS Ledger History",
        details: "All 12 prior monthly postings cleared exclusively to GL 6020. Zero prior occurrences of Office Supplies.",
        relevance_score: 0.97,
      },
      {
        id: "EVD-AWS-003",
        source_type: "INVOICE_OCR",
        title: "AWS Invoice Itemization #9910",
        details: "Item lines describe 'EC2 m6i.4xlarge compute instances' and 'S3 Standard Storage', contradicting administrative supplies.",
        relevance_score: 0.95,
      },
    ],
    tools_used: [
      { tool_name: "get_vendor_master", input_params: { vendor: "Amazon Web Services" }, output_summary: "Found Master Agreement ID AGR-AWS-2024", duration_ms: 18.4 },
      { tool_name: "get_gl_history", input_params: { vendor: "Amazon Web Services", months: 12 }, output_summary: "12 records found; 100% GL 6020", duration_ms: 24.1 },
      { tool_name: "parse_invoice_lines", input_params: { invoice_id: "INV-AWS-9910" }, output_summary: "4 cloud infrastructure line items extracted", duration_ms: 32.7 },
    ],
  },
  resolution: {
    proposed_action: "APPROVE_AND_POST",
    explanation: "Resolution Agent initially suggested posting to GL 6400 (Office Supplies) based on generic 'Amazon' purchase heuristic.",
    target_account: "6400 - Office Supplies & Administration",
    original_account: "6400 - Office Supplies & Administration",
    confidence: 0.72,
    tools_used: [
      { tool_name: "heuristic_gl_classifier", input_params: { keyword: "Amazon" }, output_summary: "Matched generic merchant catalog to GL 6400", duration_ms: 8.2 },
    ],
  },
  verifier: {
    status: "REJECTED",
    arithmetic_valid: true,
    policy_compliant: false,
    classification_valid: false,
    materiality_assessed: true,
    notes: "INDEPENDENT VERIFIER VETO: Potential incorrect posting prevented. Vendor Master Agreement AGR-AWS-2024 and invoice line items strictly require GL 6020 (Cloud Infrastructure & SaaS). Autonomous execution blocked to protect general ledger integrity.",
    blocking_reasons: [
      "Breach of Policy POL-GL-001 (Vendor Chart of Accounts Consistency)",
      "Misclassification: Cloud server compute billed to Office Supplies catalog",
    ],
    disagreement_detected: true,
    disagreement_details: "Resolution Agent proposed GL 6400; Independent Verifier determined GL 6020 is legally mandated by contract.",
    corrected_action: "POST_TO_CORRECTED_GL",
    corrected_account: "6020 - Cloud Infrastructure & SaaS Subscriptions",
  },
  autonomy_gate: {
    tier: "TIER_D",
    reason: "Independent Verifier disagreement detected; Hard execution block enforced under governance bounds.",
    can_auto_execute: false,
    requires_human_approval: false,
    is_blocked: true,
    deterministic_checks: {
      verifier_verdict: "REJECTED",
      materiality_ceiling: "$10,000.00",
      amount_tested: "$8,420.00",
      policy_breached: "POL-GL-001",
      autonomy_allowed: false,
    },
  },
  final_status: "BLOCKED",
  all_tool_calls: [
    { tool_name: "get_vendor_master", input_params: { vendor: "Amazon Web Services" }, output_summary: "AGR-AWS-2024 found", duration_ms: 18.4 },
    { tool_name: "get_gl_history", input_params: { vendor: "Amazon Web Services", months: 12 }, output_summary: "100% GL 6020", duration_ms: 24.1 },
    { tool_name: "parse_invoice_lines", input_params: { invoice_id: "INV-AWS-9910" }, output_summary: "EC2 and S3 lines", duration_ms: 32.7 },
    { tool_name: "check_policy_rules", input_params: { policy_id: "POL-GL-001" }, output_summary: "Policy violation flagged", duration_ms: 12.0 },
  ],
};

export const INITIAL_VENDORS: Vendor[] = [
  { id: 'VND-001', name: 'Amazon Web Services', normalized_name: 'AWS Cloud', tax_id: 'US-94-1340514', country: 'United States', default_gl: '6020', payment_terms: 'Net 30', risk_rating: 'LOW', status: 'ACTIVE', total_spend: 142800 },
  { id: 'VND-002', name: 'Google Cloud EMEA', normalized_name: 'Google Cloud', tax_id: 'IE-6388047V', country: 'Ireland', default_gl: '6020', payment_terms: 'Net 30', risk_rating: 'LOW', status: 'ACTIVE', total_spend: 98400 },
  { id: 'VND-003', name: 'Tata Consultancy Services', normalized_name: 'Tata Consultancy Services', tax_id: 'IN-AAACT2541F', country: 'India', default_gl: '6120', payment_terms: 'Net 45', risk_rating: 'LOW', status: 'ACTIVE', total_spend: 180000 },
  { id: 'VND-004', name: 'SAP SE', normalized_name: 'SAP SE', tax_id: 'DE-143454848', country: 'Germany', default_gl: '6020', payment_terms: 'Net 30', risk_rating: 'LOW', status: 'ACTIVE', total_spend: 240000 },
  { id: 'VND-005', name: 'CloudWorks Technologies Ltd', normalized_name: 'CloudWorks Technologies', tax_id: 'GB-992384729', country: 'United Kingdom', default_gl: '6020', payment_terms: 'Net 15', risk_rating: 'MEDIUM', status: 'ACTIVE', total_spend: 125000 },
  { id: 'VND-006', name: 'Apex Consulting Group', normalized_name: 'Apex Consulting Group', tax_id: 'US-45-9920192', country: 'United States', default_gl: '6120', payment_terms: 'Net 60', risk_rating: 'MEDIUM', status: 'ACTIVE', total_spend: 103000 },
  { id: 'VND-007', name: 'Starlight Logistics Inc', normalized_name: 'Starlight Logistics', tax_id: 'US-88-2938471', country: 'United States', default_gl: '6300', payment_terms: 'Net 30', risk_rating: 'HIGH', status: 'FLAGGED', total_spend: 42000 },
  { id: 'VND-008', name: 'Tokyo Hardware Ltd', normalized_name: 'Tokyo Hardware Ltd', tax_id: 'JP-901000102', country: 'Japan', default_gl: '1500', payment_terms: 'Net 30', risk_rating: 'LOW', status: 'ACTIVE', total_spend: 68000 },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  { id: 'PO-9001', po_number: 'PO-9001', vendor: 'Apex Consulting Group', issue_date: '2026-08-15', amount: 100000, currency: 'USD', status: 'PARTIALLY_BILLED', department: 'Enterprise Systems', permitted_variance_pct: 2.0 },
  { id: 'PO-9002', po_number: 'PO-9002', vendor: 'Starlight Logistics', issue_date: '2026-08-20', amount: 14500, currency: 'USD', status: 'CLOSED', department: 'Operations', permitted_variance_pct: 0.0 },
  { id: 'PO-TCS-004', po_number: 'PO-TCS-004', vendor: 'Tata Consultancy Services', issue_date: '2026-08-01', amount: 1250000, currency: 'INR', status: 'APPROVED', department: 'IT Infrastructure', permitted_variance_pct: 2.5 },
  { id: 'PO-SAP-001', po_number: 'PO-SAP-001', vendor: 'SAP SE', issue_date: '2026-07-01', amount: 18500, currency: 'EUR', status: 'APPROVED', department: 'Finance ERP', permitted_variance_pct: 1.0 },
];

export const INITIAL_INVOICES: Invoice[] = [
  { id: 'INV-APX-8802', invoice_number: 'INV-APX-8802', vendor: 'Apex Consulting Group', date: '2026-09-18', amount: 103000, currency: 'USD', po_number: 'PO-9001', gl_account: '6120', status: 'PENDING_MATCH' },
  { id: 'INV-STR-4401-DUP', invoice_number: 'INV-STR-4401-DUP', vendor: 'Starlight Logistics', date: '2026-09-15', amount: 14500, currency: 'USD', po_number: 'PO-9002', gl_account: '6300', status: 'DISPUTED' },
  { id: 'INV-AWS-9910', invoice_number: 'INV-AWS-9910', vendor: 'Amazon Web Services', date: '2026-09-04', amount: 8420, currency: 'USD', gl_account: '6020', status: 'DISPUTED' },
  { id: 'INV-TCS-9014', invoice_number: 'INV-TCS-9014', vendor: 'Tata Consultancy Services', date: '2026-09-12', amount: 1250000, currency: 'INR', po_number: 'PO-TCS-004', gl_account: '6120', status: 'PAID' },
];

export const INITIAL_DATA_SOURCES: DataSourceItem[] = [
  { id: 'src-bank', name: 'SVB Operating Account (***4812)', category: 'BANK', format: 'CSV', record_count: 5420, last_imported: 'Today, 08:30 AM', data_quality_pct: 99.4, currencies: ['USD', 'INR', 'EUR'], exceptions_count: 2, status: 'ACTIVE' },
  { id: 'src-gl', name: 'General Ledger Subledger Feed', category: 'GENERAL_LEDGER', format: 'CSV', record_count: 5301, last_imported: 'Today, 08:35 AM', data_quality_pct: 98.8, currencies: ['USD'], exceptions_count: 1, status: 'ACTIVE' },
  { id: 'src-inv', name: 'Vendor AP Invoices (Q3 FY26)', category: 'INVOICES', format: 'XLSX', record_count: 1420, last_imported: 'Yesterday, 04:15 PM', data_quality_pct: 96.2, currencies: ['USD', 'EUR', 'GBP', 'INR'], exceptions_count: 3, status: 'ACTIVE' },
  { id: 'src-po', name: 'Approved Purchase Orders Registry', category: 'PURCHASE_ORDERS', format: 'CSV', record_count: 890, last_imported: 'Sep 28, 2026', data_quality_pct: 99.8, currencies: ['USD', 'INR', 'EUR'], exceptions_count: 1, status: 'ACTIVE' },
  { id: 'src-vm', name: 'Enterprise Vendor Master Catalog', category: 'VENDOR_MASTER', format: 'CSV', record_count: 412, last_imported: 'Sep 25, 2026', data_quality_pct: 97.5, currencies: ['USD'], exceptions_count: 0, status: 'ACTIVE' },
];

export const INITIAL_CONNECTORS: ConnectorItem[] = [
  { id: 'conn-sap', name: 'SAP S/4HANA Cloud', category: 'ERP', logo_text: 'SAP', status: 'NOT_CONNECTED', description: 'Real-time two-way sync for journal postings and vendor subledgers.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-netsuite', name: 'Oracle NetSuite', category: 'ERP', logo_text: 'NS', status: 'NOT_CONNECTED', description: 'REST Web Services connector for automatic AP invoice synchronization.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-oracle', name: 'Oracle Financials Cloud', category: 'ERP', logo_text: 'ORA', status: 'NOT_CONNECTED', description: 'Financial consolidation subledger automated pipe.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-qb', name: 'QuickBooks Online', category: 'ERP', logo_text: 'QBO', status: 'NOT_CONNECTED', description: 'SMB and subsidiary automated ledger pull.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-xero', name: 'Xero Accounting', category: 'ERP', logo_text: 'XERO', status: 'NOT_CONNECTED', description: 'Global entity bank feed sync via bank feeds API.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-snow', name: 'Snowflake Data Cloud', category: 'WAREHOUSE', logo_text: 'SNOW', status: 'NOT_CONNECTED', description: 'Direct query ingestion from transactional enterprise data lakes.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-s3', name: 'Amazon S3 Ingestion Bucket', category: 'STORAGE', logo_text: 'S3', status: 'NOT_CONNECTED', description: 'Event-driven ingestion from corporate financial doc buckets.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
  { id: 'conn-bank', name: 'Direct Plaid / OpenBanking API', category: 'BANKING', logo_text: 'API', status: 'NOT_CONNECTED', description: 'Real-time ISO 20022 wire and statement streaming.', notes: 'Connector available in production architecture — not connected in local hackathon mode.' },
];

export const INITIAL_CONTROL_PLANE_RUNS: ControlPlaneAgentRun[] = [
  {
    id: 'RUN-RECON-01',
    agent_name: 'Deterministic Reconciliation Engine',
    role: '3-Way Match & Decimal Normalization',
    status: 'RUNNING',
    progress_pct: 92,
    current_task: 'Processing batch 18 of 20 · 4,882 / 5,420 lines verified',
    items_processed: 4882,
    total_items: 5420,
    exceptions_found: 7,
    started_at: '2026-09-05T09:00:00Z',
    duration_ms: 1240,
    verifier_result: 'VERIFIED',
    evidence_count: 5301,
    tools_invoked: ['bank_feed_matcher', 'decimal_variance_calc', 'currency_normalizer'],
  },
  {
    id: 'RUN-DUP-01',
    agent_name: 'Duplicate Investigator Agent',
    role: 'Multi-Signal Weighted Fraud & Repetition Analysis',
    status: 'COMPLETED',
    progress_pct: 100,
    current_task: 'Completed scan across 5,420 entries · 1 duplicate blocked',
    items_processed: 5420,
    total_items: 5420,
    exceptions_found: 1,
    started_at: '2026-09-05T09:01:15Z',
    duration_ms: 840,
    verifier_result: 'VERIFIED',
    evidence_count: 14,
    tools_invoked: ['invoice_number_matcher', 'fuzzy_vendor_sim', 'temporal_proximity_scan'],
  },
  {
    id: 'RUN-VAR-01',
    agent_name: 'PO Variance Forensic Agent',
    role: 'Tolerance Boundary & Contract Investigation',
    status: 'RUNNING',
    progress_pct: 66,
    current_task: 'Comparing Apex Advisory INV-APX-8802 against PO-9001 baseline',
    items_processed: 8,
    total_items: 12,
    exceptions_found: 2,
    started_at: '2026-09-05T09:02:00Z',
    duration_ms: 1120,
    verifier_result: 'WAITING_FOR_DATA',
    evidence_count: 6,
    tools_invoked: ['po_terms_extractor', 'materiality_calculator', 'prior_variance_history'],
  },
  {
    id: 'RUN-VER-01',
    agent_name: 'Independent Adversarial Verifier',
    role: 'Adversarial Check & Self-Approval Prevention',
    status: 'VERIFYING',
    progress_pct: 75,
    current_task: 'Audit check on AWS proposal (GL 6400 vs Master Agreement GL 6020)',
    items_processed: 6,
    total_items: 8,
    exceptions_found: 1,
    started_at: '2026-09-05T09:03:00Z',
    duration_ms: 950,
    verifier_result: 'FAILED_VERIFICATION',
    evidence_count: 8,
    tools_invoked: ['vendor_contract_cross_check', 'arithmetic_verifier', 'policy_compliance_checker'],
  },
  {
    id: 'RUN-HUM-01',
    agent_name: 'Human Review Center Gate',
    role: 'Controller Sign-Off & Governance Orchestration',
    status: 'WAITING_FOR_HUMAN',
    progress_pct: 35,
    current_task: 'Awaiting Controller decision on Tier C material exceptions',
    items_processed: 1,
    total_items: 3,
    exceptions_found: 0,
    started_at: '2026-09-05T09:04:00Z',
    duration_ms: 0,
    evidence_count: 4,
    tools_invoked: ['governance_tier_router', 'audit_event_recorder'],
  },
];

export const INITIAL_EVAL_REPORTS: Record<string, EvaluationReport> = {
  V1: {
    run_id: "EVAL-2026-0901-V1",
    agent_version: "V1",
    timestamp: "2026-09-01T14:22:00Z",
    total_cases: 40,
    passed_cases: 31,
    accuracy: 77.5,
    false_auto_approval_rate: 15.0,
    escalation_precision: 71.4,
    completion_rate: 100.0,
    average_latency_ms: 142.0,
    estimated_cost_usd: 0.0,
    failure_breakdown: {
      RULE_FAILURE: 3,
      POLICY_FAILURE: 2,
      CLASSIFICATION_FAILURE: 2,
      MISSING_EVIDENCE: 2,
    },
    failed_case_ids: ["TC-004", "TC-009", "TC-014", "TC-019", "TC-023", "TC-028", "TC-033", "TC-037", "TC-040"],
  },
  V2: {
    run_id: "EVAL-2026-0905-V2",
    agent_version: "V2",
    timestamp: "2026-09-05T08:15:00Z",
    total_cases: 40,
    passed_cases: 38,
    accuracy: 95.0,
    false_auto_approval_rate: 2.5,
    escalation_precision: 93.3,
    completion_rate: 100.0,
    average_latency_ms: 118.0,
    estimated_cost_usd: 0.0,
    failure_breakdown: {
      MISSING_EVIDENCE: 1,
      AMBIGUOUS_INPUT: 1,
    },
    failed_case_ids: ["TC-019", "TC-037"],
  },
};
